// The fiction edition of the AI Nutrition Label, as data. One source of truth for /api/v1/vocab/fiction and
// for /schemas; the label page itself (public/label/fiction/) keeps its own copy in label.jsx until it is
// built from this file, and a test pins the two together so they cannot drift.
//
// Shape: six tiers picked by a score, twenty ingredients in five groups, each at one of four levels. The
// score is the sum of weight × level multiplier, clamped to 100; the tier is the first whose max the score
// does not exceed. Production lines (cover, audiobook, synopsis, blurb) show on the label and weigh nothing:
// they describe the package, not the prose.

export const FICTION_LABEL_VERSION = "0.2";

export const FICTION_TIERS = [
  { code: "H",  name: "HUMAN-MADE",   tag: "100% HUMAN PROSE",           max: 0,   blurb: "Every word written by the author. No AI in the loop." },
  { code: "HE", name: "HUMAN+EDITOR", tag: "AI USED AS EDITOR ONLY",     max: 15,  blurb: "Author wrote every word. AI used to flag issues; author revised by hand." },
  { code: "HP", name: "POLISHED",     tag: "AI COPY-EDITED",             max: 30,  blurb: "Human-written prose. AI applied for grammar, typos, and line-level cleanup." },
  { code: "AA", name: "AI-ASSISTED",  tag: "SOME AI-GENERATED PASSAGES", max: 55,  blurb: "Author and AI collaborated. AI generated portions of the prose." },
  { code: "AC", name: "CO-WRITTEN",   tag: "SUBSTANTIAL AI PROSE",       max: 80,  blurb: "Significant portions of the prose were generated by AI and revised by a human." },
  { code: "AI", name: "AI-AUTHORED",  tag: "AI-GENERATED PROSE",         max: 200, blurb: "AI generated the prose. Human supervised, prompted, or curated." },
] as const;

export type FictionLevel = "none" | "advisory" | "applied" | "generated";

export const FICTION_LEVELS: Record<FictionLevel, { label: string; short: string; multiplier: number; means: string }> = {
  none:      { label: "None",          short: "—",         multiplier: 0,    means: "AI never came near this category." },
  advisory:  { label: "Advisory only", short: "Advisory",  multiplier: 0.05, means: "AI flagged an issue. The author resolved it by hand." },
  applied:   { label: "AI-applied",    short: "Applied",   multiplier: 0.4,  means: "AI made the change directly. Author reviewed." },
  generated: { label: "AI-generated",  short: "Generated", multiplier: 1,    means: "AI produced new text or imagery from scratch." },
};

export interface FictionIngredient { id: string; group: string; label: string; sub: string; allow: FictionLevel[]; weight: number }

export const FICTION_INGREDIENTS: FictionIngredient[] = [
  { id: "brainstorm",    group: "PRE-WRITING", label: "Brainstorming & ideation",    sub: "premise, themes, what-ifs",          allow: ["none", "advisory", "applied", "generated"], weight: 6 },
  { id: "outline",       group: "PRE-WRITING", label: "Outline & structure",         sub: "chapter beats, plot scaffold",       allow: ["none", "advisory", "applied", "generated"], weight: 10 },
  { id: "bible",         group: "PRE-WRITING", label: "Story bible / worldbuilding", sub: "characters, settings, lore",         allow: ["none", "advisory", "applied", "generated"], weight: 8 },
  { id: "prose",         group: "PROSE",       label: "Prose generation",            sub: "narrative paragraphs, scenes",       allow: ["none", "generated"],                        weight: 60 },
  { id: "dialog",        group: "PROSE",       label: "Dialog generation",           sub: "character speech",                   allow: ["none", "generated"],                        weight: 35 },
  { id: "rewrite",       group: "PROSE",       label: "Voice / passage rewrite",     sub: "in author's style",                  allow: ["none", "applied", "generated"],             weight: 30 },
  { id: "developmental", group: "EDITORIAL",   label: "Developmental edit",          sub: "structure, arc, pacing notes",       allow: ["none", "advisory"],                         weight: 4 },
  { id: "line",          group: "EDITORIAL",   label: "Line edit",                   sub: "sentence-level rephrasing",          allow: ["none", "advisory", "applied"],              weight: 18 },
  { id: "copy",          group: "EDITORIAL",   label: "Copy edit",                   sub: "grammar, punctuation",               allow: ["none", "advisory", "applied"],              weight: 8 },
  { id: "spell",         group: "EDITORIAL",   label: "Spelling & typos",            sub: "mechanical proofing",                allow: ["none", "advisory", "applied"],              weight: 3 },
  { id: "continuity",    group: "ANALYSIS",    label: "Continuity audit",            sub: "characters, objects, settings",      allow: ["none", "advisory"],                         weight: 2 },
  { id: "chronology",    group: "ANALYSIS",    label: "Chronology audit",            sub: "timeline consistency",               allow: ["none", "advisory"],                         weight: 2 },
  { id: "pov",           group: "ANALYSIS",    label: "POV discipline",              sub: "viewpoint consistency",              allow: ["none", "advisory"],                         weight: 2 },
  { id: "pacing",        group: "ANALYSIS",    label: "Pacing analysis",             sub: "beat structure, tension arc",        allow: ["none", "advisory"],                         weight: 2 },
  { id: "research",      group: "ANALYSIS",    label: "Research assistance",         sub: "facts, references",                  allow: ["none", "advisory", "applied"],              weight: 4 },
  { id: "translation",   group: "PRODUCTION",  label: "Translation",                 sub: "from another language",              allow: ["none", "applied", "generated"],             weight: 25 },
  { id: "cover",         group: "PRODUCTION",  label: "Cover art",                   sub: "front jacket image",                 allow: ["none", "applied", "generated"],             weight: 0 },
  { id: "audiobook",     group: "PRODUCTION",  label: "Audiobook narration",         sub: "synthetic voice / TTS",              allow: ["none", "applied", "generated"],             weight: 0 },
  { id: "synopsis",      group: "PRODUCTION",  label: "Synopsis",                    sub: "plot summary for pitch / catalog",   allow: ["none", "advisory", "applied", "generated"], weight: 0 },
  { id: "blurb",         group: "PRODUCTION",  label: "Marketing copy",              sub: "back-cover blurb, query letter",     allow: ["none", "advisory", "applied", "generated"], weight: 0 },
];

/** The same arithmetic the label page runs: Σ weight × multiplier, one decimal, clamped to 100. */
export function fictionScore(values: Record<string, FictionLevel | undefined>): number {
  let score = 0;
  for (const ing of FICTION_INGREDIENTS) {
    const v = values[ing.id] ?? "none";
    if (v === "none") continue;
    score += ing.weight * FICTION_LEVELS[v].multiplier;
  }
  return Math.min(100, Math.round(score * 10) / 10);
}

export function fictionTier(score: number) {
  for (const t of FICTION_TIERS) if (score <= t.max) return t;
  return FICTION_TIERS[FICTION_TIERS.length - 1];
}

export function fictionVocabJson(origin: string) {
  return {
    label: "AI Nutrition Label",
    edition: "fiction",
    version: FICTION_LABEL_VERSION,
    page: `${origin}/label/fiction/`,
    directory: `${origin}/schemas`,
    license: "CC-BY-4.0",
    self_reported: true,
    score: "sum over ingredients of weight × level multiplier, one decimal place, clamped to 100; production lines weigh 0",
    tiers: FICTION_TIERS,
    levels: FICTION_LEVELS,
    ingredients: FICTION_INGREDIENTS,
  };
}
